name: Deploy React App
on: push
jobs:
  test-app:
    runs-on: ubuntu-latest
      steps: 
        - name: Get code from git
          uses: actions/checkout@v3
        - name: Install dependecies
          run : npm ci
        - name: Run tests
          run : npm run test